# Generated by Django 2.2.7 on 2020-01-14 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='SingleAnsQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_ans_ques', models.CharField(max_length=100)),
                ('single_ans_ques_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_ans_ques', to='question.FormInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MultiAnsQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('multi_ans_ques', models.CharField(max_length=100)),
                ('multi_ans_ques_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_ans_ques', to='question.FormInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LinearScaleQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linear_scale_ques', models.CharField(max_length=100)),
                ('linear_scale_ques_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='linear_scale', to='question.FormInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FileQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ques', models.CharField(max_length=50)),
                ('file_ques_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_ques', to='question.FormInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_ques', models.CharField(max_length=100)),
                ('options', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('checkbox_ques_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_ques', to='question.FormInfo')),
            ],
        ),
    ]
