# Generated by Django 2.2.7 on 2020-01-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200114_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminfo',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='forminfo',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
