# Generated by Django 2.2.7 on 2020-01-19 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0003_auto_20200119_0620'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.FormInfo')),
                ('username_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='SingleAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_ans', models.CharField(max_length=100)),
                ('answer_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_answer_info', to='answer.AnswerInfo')),
                ('single_ans_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_ans', to='question.SingleAnsQues')),
            ],
        ),
        migrations.CreateModel(
            name='MultiAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_ans', models.CharField(max_length=50)),
                ('answer_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_answer_info', to='answer.AnswerInfo')),
                ('multi_ans_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.MultiAnsQues')),
            ],
        ),
        migrations.CreateModel(
            name='LinearAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linear_ans', models.IntegerField()),
                ('answer_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='linear_answer_info', to='answer.AnswerInfo')),
                ('linear_ans_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.LinearScaleQues')),
            ],
        ),
        migrations.CreateModel(
            name='FileAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ans', models.FileField(upload_to='')),
                ('answer_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_answer_info', to='answer.AnswerInfo')),
                ('file_ans_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.FileQues')),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_ans', models.CharField(max_length=50)),
                ('answer_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_answer_info', to='answer.AnswerInfo')),
                ('check_ans_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.CheckboxQues')),
            ],
        ),
    ]
