# Generated by Django 2.2.7 on 2020-02-09 09:03

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200119_0620'),
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinearAns',
            new_name='LinearScaleAns',
        ),
        migrations.AlterField(
            model_name='answerinfo',
            name='question_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_info', to='question.FormInfo'),
        ),
        migrations.AlterField(
            model_name='checkboxans',
            name='checkbox_ans',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
