# Generated by Django 2.2.7 on 2020-02-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20200209_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinfo',
            name='question_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.FormInfo'),
        ),
        migrations.AlterField(
            model_name='fileans',
            name='file_ans_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_answer_link', to='question.FileQues'),
        ),
    ]
